# Generated by Django 5.1.7 on 2025-03-22 19:12

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("users", "0003_patientreport"),
    ]

    operations = [
        migrations.AddField(
            model_name="patientreport",
            name="report_type",
            field=models.CharField(
                choices=[
                    ("video", "Video Consultation"),
                    ("lab", "Lab Report"),
                    ("other", "Other Report"),
                ],
                default="other",
                max_length=20,
            ),
        ),
    ]
