# Generated by Django 5.1.7 on 2025-03-30 07:09

import users.models
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("users", "0005_doctorreport"),
    ]

    operations = [
        migrations.AlterField(
            model_name="doctorreport",
            name="file",
            field=models.FileField(upload_to=users.models.doctor_report_upload_path),
        ),
        migrations.AlterField(
            model_name="patientreport",
            name="file",
            field=models.FileField(upload_to=users.models.patient_report_upload_path),
        ),
    ]
