# Generated by Django 5.1.7 on 2025-04-29 10:26

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("users", "0008_otpverification"),
    ]

    operations = [
        migrations.AddField(
            model_name="customuser",
            name="consultation_fee",
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
    ]
