# Generated by Django 5.1.7 on 2025-04-29 15:54

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("users", "0011_doctoravailability"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="appointment",
            options={"ordering": ["-date", "-time"]},
        ),
        migrations.AddField(
            model_name="appointment",
            name="is_recurring",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="appointment",
            name="title",
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name="appointment",
            name="doctor",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="doctor_appointments",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AlterField(
            model_name="appointment",
            name="patient",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="patient_appointments",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AlterField(
            model_name="appointment",
            name="status",
            field=models.CharField(default="pending", max_length=20),
        ),
        migrations.AlterField(
            model_name="appointment",
            name="time",
            field=models.CharField(max_length=10),
        ),
    ]
